services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./server"
    depends_on:
      - caddy
      - buildkit
    develop:
      watch:
        - action: rebuild
          path: ./
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      BUILDKIT_HOST: "docker-container://buildkit"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    image: "api:dev"
    networks:
      - "appa_net"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - api_data:/data
      - railpack_cache:/tmp/railpack

  buildkit:
    image: moby/buildkit:latest
    container_name: buildkit
    networks:
      - "appa_net"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  caddy:
    image: caddy:2.11.2-alpine
    ports:
      - "80:80"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - "appa_net"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./ui/src
          target: /app/src
    image: "ui:dev"
    networks:
      - "appa_net"
    volumes:
      - ./ui:/app
      - /app/node_modules

volumes:
  api_data:
  caddy_data:
  caddy_config:
  railpack_cache:

networks:
  appa_net:
    name: appa_net
    driver: bridge