---
galaxy_info:
  author: theolujay
  description: Access control hardening for Appa-managed hosts
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - access
    - security
    - hardening
    - pam
    - sudo

dependencies: []
