package data

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"errors"
	"maps"
	"time"

	vd "github.com/theolujay/appa/internal/validator"

	"github.com/lib/pq"
	"golang.org/x/crypto/bcrypt"
)

var (
	ErrDuplicateEmail = errors.New("duplicate email")
)

var AnonymousUser = &User{}

func (u *User) IsAnonymous() bool {
	return u == AnonymousUser || u == nil
}

type User struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  password  `json:"-"`
	Activated bool      `json:"activated"`
	Version   int       `json:"-"`
}

type password struct {
	plaintext string
	hash      []byte
}

type UserModel struct {
	DB *sql.DB
}

type UserModeler interface {
	Insert(user *User) error
	GetByEmail(email string) (*User, error)
	Update(user *User) error
	GetForToken(tokenScope string, tokenPlaintext string) (*User, error)
}

// The Set() method calculates the bcrypt has of a plaintext password
// and stores both the hash and the plaintext versions in the struct.
func (p *password) Set(plaintextPassword string) error {
	hash, err := bcrypt.GenerateFromPassword([]byte(plaintextPassword), 12)
	if err != nil {
		return err
	}

	p.plaintext = plaintextPassword
	p.hash = hash

	return nil
}

// The Matches() method checks whether the provided plaintext password
// matches the hashed password stored in the struct, returning true if
// it matches and false otherwise.
func (p *password) Matches(plaintextPassword string) (bool, error) {
	err := bcrypt.CompareHashAndPassword(p.hash, []byte(plaintextPassword))
	if err != nil {
		switch {
		case errors.Is(err, bcrypt.ErrMismatchedHashAndPassword):
			return false, nil
		default:
			return false, err
		}
	}

	return true, nil
}

func ValidateEmail(email string) vd.Error {
	v := vd.New()
	v.Check(email != "", "email", "must be provided")
	v.Check(vd.Matches(email, vd.EmailRX), "email", "must be a valid email address")
	return v.Errors
}

func ValidatePasswordPlaintext(password string) vd.Error {
	v := vd.New()
	v.Check(password != "", "password", "must be provided")
	v.Check(len(password) >= 8, "password", "must be at least 8 bytes long")
	v.Check(len(password) <= 72, "password", "must not be more than 72 bytes long")

	return v.Errors
}

func ValidateUser(user *User) vd.Error {
	v := vd.New()
	v.Check(user.Name != "", "name", "must be provided")
	v.Check(len(user.Name) <= 500, "name", "must not be more than 500 bytes long")

	maps.Copy(v.Errors, ValidateEmail(user.Email))

	if user.Password.plaintext != "" {
		maps.Copy(v.Errors, ValidatePasswordPlaintext(user.Password.plaintext))
	}

	// If the password hash is ever nil, this will be due to a logic error in the
	// codebase (perhaps we forgot to set a password for the user). It's useful
	// sanity check to include here, but it's not a problem with the data provided
	// by the client. So rather than adding an error to the validation we raise a
	// panic instead.
	if user.Password.hash == nil {
		panic("missing password hash for user")
	}
	return v.Errors
}

// Insert a new record in the database for the user. Note that the id, created_at
// and version fields are all automatically generated by the database, so use the
// RETURNING clause to read them into the User struct after the insert.
func (m UserModel) Insert(user *User) error {
	query := `
		INSERT INTO users (name, email, password_hash, activated)
		VALUES ($1, $2, $3, $4)
		RETURNING id, created_at, version
	`
	args := []any{user.Name, user.Email, user.Password.hash, user.Activated}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	err := m.DB.QueryRowContext(ctx, query, args...).Scan(&user.ID, &user.CreatedAt, &user.Version)
	if err != nil {

		if pqErr, ok := errors.AsType[*pq.Error](err); ok {
			if pqErr.Code == "23505" && pqErr.Constraint == "users_email_key" {
				return ErrDuplicateEmail
			}
		}
		return err
	}

	return nil
}

// Retrieve the User details from the database based on the user's email address.
// Because we have a UNIQUE constraint on the email column, this SQL query will
// only return one record (or none at all, in which case we return a
// ErrRecordNotFound error).
func (m UserModel) GetByEmail(email string) (*User, error) {
	query := `
		SELECT id, created_at, name, email, password_hash, activated, version
		FROM users
		WHERE email = $1
	`
	var user User

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	err := m.DB.QueryRowContext(ctx, query, email).Scan(
		&user.ID,
		&user.CreatedAt,
		&user.Name,
		&user.Email,
		&user.Password.hash,
		&user.Activated,
		&user.Version,
	)

	if err != nil {
		switch {
		case errors.Is(err, sql.ErrNoRows):
			return nil, ErrRecordNotFound
		default:
			return nil, err
		}
	}

	return &user, nil
}

// Update the details for a specific user. We check against the version field
// to help prevent any race conditions during the request cycle, just like we
// did when updating a movie. And also check for violation of the
// "users_email_key" constraint when performing the update.
func (m UserModel) Update(user *User) error {
	query := `
		UPDATE users
		SET name = $1, email = $2, password_hash = $3, activated = $4, version = version + 1
		WHERE id = $5 AND version = $6
		RETURNING version
	`
	args := []any{
		user.Name,
		user.Email,
		user.Password.hash,
		user.Activated,
		user.ID,
		user.Version,
	}
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	err := m.DB.QueryRowContext(ctx, query, args...).Scan(&user.Version)

	if err != nil {
		var pqErr *pq.Error
		switch {
		case errors.As(err, &pqErr):
			if pqErr.Code == "23505" && pqErr.Constraint == "users_email_key" {
				return ErrDuplicateEmail
			}
		case errors.Is(err, sql.ErrNoRows):
			return ErrEditConflict
		default:
			return err
		}
	}

	return nil

}

func (m UserModel) GetForToken(tokenScope string, tokenPlaintext string) (*User, error) {
	tokenHash := sha256.Sum256([]byte(tokenPlaintext))

	query := `
		SELECT users.id, users.created_at, users.name, users.email, users.password_hash, users.activated, users.version
		FROM users
		INNER JOIN tokens
		ON users.id = tokens.user_id
		WHERE tokens.hash = $1
		AND tokens.scope = $2
		AND tokens.expiry > $3
	`

	args := []any{tokenHash[:], tokenScope, time.Now()}

	var user User

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	err := m.DB.QueryRowContext(ctx, query, args...).Scan(
		&user.ID,
		&user.CreatedAt,
		&user.Name,
		&user.Email,
		&user.Password.hash,
		&user.Activated,
		&user.Version,
	)
	if err != nil {
		switch {
		case errors.Is(err, sql.ErrNoRows):
			return nil, ErrRecordNotFound
		default:
			return nil, err
		}
	}
	return &user, nil
}
