---
- name: Restart auditd
  ansible.builtin.service:
    name: auditd
    state: restarted
  listen: restart auditd

- name: Reload audit rules
  ansible.builtin.command: augenrules --load
  register: auditd_load
  changed_when: true
  failed_when: auditd_load.rc != 0 and 'No change' not in auditd_load.stdout
