package pipeline

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
)

const (
	railpackPlanFile = "railpack-plan.json"
	railpackInfoFile = "railpack-info.json"
)

// prepareBuild clones the source repository and runs `railpack prepareBuild` to
// generate a BuildKit build plan. It streams every line of output to the
// hub and persists it to the database as it arrives.
func (p *Pipeline) prepareBuild(ctx context.Context, id int64, source string) (string, error) {
	buildDir, err := p.cloneRepo(ctx, source, id)
	if err != nil {
		return "", fmt.Errorf("%w: %w", errPrepareFailed, err)
	}

	p.logLine(id, phaseBuild, "preparing...")

	planFile := filepath.Join(buildDir, railpackPlanFile)
	infoFile := filepath.Join(buildDir, railpackInfoFile)

	cmd := exec.CommandContext(
		ctx,
		"railpack",
		"prepare",
		buildDir,
		"--plan-out",
		planFile,
		"--info-out",
		infoFile,
	)

	// Pass the user's environment variables
	//
	// TODO: implement better handling for secrets
	d, err := p.deployment.Get(id)
	if err != nil {
		return "", fmt.Errorf("%w: %w", errPrepareFailed, err)
	}
	if d.EnvVars != nil && *d.EnvVars != "" {
		envLines := strings.SplitSeq(*d.EnvVars, "\n")
		for line := range envLines {
			line = strings.TrimSpace(line)
			if line != "" {
				cmd.Args = append(cmd.Args, "--env", line)
			}
		}
	}

	err = p.pipeLogs(cmd, id, phaseBuild)
	if err != nil {
		return "", fmt.Errorf("%w: %w", errPrepareFailed, err)
	}

	return buildDir, nil
}

// buildImage runs `buildctl buildImage` with the Railpack frontend to produce a
// container image from the plan generated by Prepare. It returns the
// image tag on success.
func (p *Pipeline) buildImage(ctx context.Context, id int64, buildDir string) (string, error) {
	// TODO: consider versioning for rollback features
	imageTag := fmt.Sprintf("appa-%d", id)
	railpackVersion := os.Getenv("RAILPACK_VERSION")

	if railpackVersion == "" {
		return "", fmt.Errorf("%w: railpack version not set", errBuildFailed)
	}

	p.logLine(id, phaseBuild, "building...")

	buildctl := exec.CommandContext(
		ctx,
		"buildctl",
		"build",
		"--local",
		fmt.Sprintf("context=%s", buildDir),
		"--local",
		fmt.Sprintf("dockerfile=%s", buildDir),
		"--frontend=gateway.v0",
		"--opt",
		fmt.Sprintf("source=ghcr.io/railwayapp/railpack-frontend:%s", railpackVersion),
		"--output",
		fmt.Sprintf("type=docker,name=%s", imageTag),
	)

	dockerLoad := exec.CommandContext(ctx, "docker", "load")

	// Pipe buildctl's stdout (docker image tarball) into docker load's stdin
	out, err := buildctl.StdoutPipe()
	if err != nil {
		return "", fmt.Errorf("%w: %w", errBuildFailed, err)
	}
	dockerLoad.Stdin = out

	// Stream stderr (BuildKit progress output) through the logging system
	stderr, err := buildctl.StderrPipe()
	if err != nil {
		return "", fmt.Errorf("%w: %w", errBuildFailed, err)
	}

	if err := dockerLoad.Start(); err != nil {
		return "", fmt.Errorf("%w: %w", errBuildFailed, err)
	}
	if err := buildctl.Start(); err != nil {
		return "", fmt.Errorf("%w: %w", errBuildFailed, err)
	}

	var wg sync.WaitGroup
	wg.Go(func() {
		defer wg.Done()
		defer p.recoverFunc(id, phaseBuild)
		p.streamLogs(id, phaseBuild, stderr)
	})

	buildErr := buildctl.Wait()
	wg.Wait()
	loadErr := dockerLoad.Wait()

	if buildErr != nil {
		return "", fmt.Errorf("%w: %w", errBuildFailed, buildErr)
	}
	if loadErr != nil {
		return "", fmt.Errorf("%w: %w", errBuildFailed, loadErr)
	}

	return imageTag, nil
}

func (p *Pipeline) streamLogs(id int64, phase string, r io.Reader) {
	s := bufio.NewScanner(r)
	for s.Scan() {
		p.logLine(id, phase, s.Text())
	}
	if err := s.Err(); err != nil {
		p.logLine(id, phase, fmt.Sprintf("log stream error: %v", err))
	}
}

func (p *Pipeline) cloneRepo(ctx context.Context, source string, id int64) (string, error) {
	// Check if source is a local directory (for uploads) or a git URL
	isLocal := false
	if info, err := os.Stat(source); err == nil && info.IsDir() {
		isLocal = true
	}

	if isLocal {
		p.logLine(id, phaseBuild, "using uploaded project files")
		return source, nil
	}

	// Create a temporary directory to clone the source repository into,
	// then clean it up afterwards
	tmpDir, err := os.MkdirTemp("", "appa-build-*")
	if err != nil {
		return "", fmt.Errorf("%w: %w", errPrepareFailed, err)
	}

	buildDir := tmpDir

	// Clone the repository into the temp directory, and stream it in logs
	p.logLine(id, phaseBuild, fmt.Sprintf("cloning %s", source))

	cloneCmd := exec.CommandContext(ctx, "git", "clone", "--quiet", "--depth=1", source, buildDir)
	cloneOut, err := cloneCmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("%w: git clone failed: %s", errPrepareFailed, string(cloneOut))
	}
	p.logLine(id, phaseBuild, "clone complete")

	return buildDir, nil
}

// pipeLogs attaches pipes to a command's stdout and stderr, streams each
// line to the hub and database, then waits for the command to finish.
func (p *Pipeline) pipeLogs(cmd *exec.Cmd, id int64, phase string) error {

	// Attach pipes to stdout and stderr so they're read as build runs.
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("%w: %w", errPrepareFailed, err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("%w: %w", errPrepareFailed, err)
	}

	// Launches the process but doesn't wait for it to finish and returns control
	// so pipes can be read.
	err = cmd.Start()
	if err != nil {
		return fmt.Errorf("%w: %w", errPrepareFailed, err)
	}

	// Stream both stdout and stderr to the hub and database. Merge them into
	// a single log stream to client.
	// WaitGroup allows to drain both pipes concurrently by waiting for both
	// to finish before calling cmd.Wait().
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		defer wg.Done()
		defer p.recoverFunc(id, phase)
		p.streamLogs(id, phase, stdout)
	}()
	go func() {
		defer wg.Done()
		defer p.recoverFunc(id, phase)
		p.streamLogs(id, phase, stderr)
	}()
	wg.Wait()

	// Now wait for the process to exit...
	// cmd.Wait() returns an error if the process exits with a non-zero code,
	// which would mean the build failed.
	if err := cmd.Wait(); err != nil {
		return fmt.Errorf("%w: %w", errPrepareFailed, err)
	}
	return nil
}
