package pipeline

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
	"sync"

	"github.com/theolujay/appa/internal/data"
	"github.com/theolujay/appa/internal/hub"
)

// Prepare clones the source repository and runs `railpack prepare` to
// generate a BuildKit build plan. It streams every line of output to the
// hub and persists it to the database as it arrives.
func (p *Pipeline) Prepare(ctx context.Context, id int64, source string) error {
	status := data.BUILDING

	deployment, err := p.deployment.UpdateAndGet(id, data.DeploymentUpdate{Status: &status})
	if err != nil {
		return fmt.Errorf("failed to update status: %w", err)
	}

	p.hub.PublishStatus(id, status, "")

	buildDir, err := p.cloneRepo(ctx, source, id)
	if err != nil {
		return err
	}

	cmd := exec.CommandContext(
		ctx,
		"railpack",
		"prepare",
		buildDir,
		"--plan-out",
		"./railpack-plan.json",
		"--info-out",
		"./railpack-info.json",
	)

	// Pass the user's environment variables
	// TODO: implement better handling for secrets
	if deployment.EnvVars != nil && *deployment.EnvVars != "" {
		envLines := strings.SplitSeq(*deployment.EnvVars, "\n")
		for line := range envLines {
			line = strings.TrimSpace(line)
			if line != "" {
				cmd.Args = append(cmd.Args, "--env", line)
			}
		}
	}

	return p.PipeLogs(cmd, id, phaseBuild)
}

// Build runs `buildctl build` with the Railpack frontend to produce a
// container image from the plan generated by Prepare. It returns the
// image tag on success.
func (p *Pipeline) Build(ctx context.Context, id int64) (string, error) {
	// TODO: consider versioning for rollback features
	imageTag := fmt.Sprintf("appa-%d", id)

	cmd := exec.CommandContext(
		ctx,
		"buildctl",
		"build",
		"--local",
		"context=./",
		"--local",
		"dockerfile=./railpack-plan.json",
		"--frontend=gateway.v0",
		"--opt",
		"source=ghcr.io/railwayapp/railpack-frontend",
		"--output",
		fmt.Sprintf("type=docker,name=%s", imageTag),
	)
	err := p.PipeLogs(cmd, id, phaseBuild)
	if err != nil {
		return "", err
	}

	return imageTag, nil
}

func (p *Pipeline) streamLogs(id int64, phase string, r io.Reader) {
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := scanner.Text()

		// First persist. If the hub publish fails for any reason, the log
		// lines still live in the database for scroll-back
		logID, err := p.deployment.AppendLog(id, phase, line)
		if err != nil {
			_ = err
		}

		p.hub.PublishLog(id, hub.LogMessage{ID: logID, Line: line})
	}
}

func (p *Pipeline) cloneRepo(ctx context.Context, source string, id int64) (string, error) {
	// Check if source is a local directory (for uploads) or a git URL
	isLocal := false
	if info, err := os.Stat(source); err == nil && info.IsDir() {
		isLocal = true
	}

	var buildDir string
	if isLocal {
		buildDir = source
		logID, _ := p.deployment.AppendLog(id, phaseBuild, "using uploaded project files")
		p.hub.PublishLog(id, hub.LogMessage{ID: logID, Line: "using uploaded project files"})
	} else {
		// Create a temporary directory to clone the source repository into,
		// then clean it up afterwards
		tmpDir, err := os.MkdirTemp("", "appa-build-*")
		if err != nil {
			return "", fmt.Errorf("failed to create temp dir: %w", err)
		}
		defer os.RemoveAll(tmpDir)
		buildDir = tmpDir

		// Clone the repository into the temp directory, and stream it in logs
		msg := fmt.Sprintf("cloning %s", source)
		logID, _ := p.deployment.AppendLog(id, phaseBuild, msg)
		p.hub.PublishLog(id, hub.LogMessage{ID: logID, Line: msg})

		cloneCmd := exec.CommandContext(ctx, "git", "clone", "--quiet", "--depth=1", source, buildDir)
		cloneOut, err := cloneCmd.CombinedOutput()
		if err != nil {
			return "", fmt.Errorf("git clone failed: %s", string(cloneOut))
		}
		logID, _ = p.deployment.AppendLog(id, phaseBuild, "clone complete")
		p.hub.PublishLog(id, hub.LogMessage{ID: logID, Line: "clone complete"})
	}

	return buildDir, nil
}

// PipeLogs attaches pipes to a command's stdout and stderr, streams each
// line to the hub and database, then waits for the command to finish.
func (p *Pipeline) PipeLogs(cmd *exec.Cmd, id int64, phase string) error {

	// Attach pipes to stdout and stderr so they're read as build runs.
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("failed to create stdout pipe: %w", err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("failed to create stderr pipe: %w", err)
	}

	// Launches the process but doesn't wait for it to finish and returns control
	// so pipes can be read.
	err = cmd.Start()
	if err != nil {
		return fmt.Errorf("failed to start command: %w", err)
	}

	// Stream both stdout and stderr to the hub and database. Merge them into
	// a single log stream to client.
	// WaitGroup allows to drain both pipes concurrently by waiting for both
	// to finish before calling cmd.Wait().
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); p.streamLogs(id, phase, stdout) }()
	go func() { defer wg.Done(); p.streamLogs(id, phase, stderr) }()
	wg.Wait()

	// Now wait for the process to exit...
	// cmd.Wait() returns an error if the process exits with a non-zero code,
	// which would mean the build failed.
	return cmd.Wait()
}
